### ISSUE TITLE
Rendering FPS is low, even without Filtering

### ISSUE THREAD

**Issue by hahmed1** [frankschlegel/core-image-by-example#3]
I am trying to decide if it is worth using SwiftUI for a real-time video processing app I am working on, and I found this project.  The code is very useful for a beginner like me who is new to SwiftUI, especially since I don't see any other SwiftUI projects that integrate MetalKit.  However, my main concern is the low frame rate I have observed in this code compared to UIKit. 

In my UIKit metal rendering demo code, I am easily able to hit 60 FPS (it is very similar to this project: capture Camera frames as pixelBuffers with an AVCapture session, convert pixel buffs to CIImages, and render them on a Metal-accelerated view).  In this SwiftUI project however, rendering is happening at approximately 15 FPS, even after commenting out the filtering code: 

            .map { [weak filter = self.filter] inputImage -> CIImage? in
                filter?.setValue(inputImage, forKey: kCIInputImageKey)
                return filter?.outputImage
            }          

If I understand correctly, removing the lines above should cause the FilterController to only convert the pixelbuffer to a CIImage, which shouldn't be so slow.  Is there something else I am missing which may be causing the low frame-rate, or is this expected (perhaps some intrinsic limitation with SwiftUI and/or Combine)?

**Comment by frankschlegel** [comment]
Hey, sorry for the very late response!

The current setup uses the `.photo` session preset, which outputs buffers at 30 FPS in a pretty large size (roughly the size of the screen). This might impact performance. In a real-world scenario, one might want to downscale those images before filtering them.

For testing purposes, I set the session preset to `.hd4K3840x2160` and picked a format for the `videoDevice` that allows 60 FPS capture and I was able to get a steady 60 FPS output (unfiltered) and ~55 FPS with the built-in comic filter. I tested on iPad Pro (with M1) and an iPhone 11 Pro Max. What device are you using?

But you are right, I think there is still some room for improvements, especially at the border between AVFoundation and UI. I can hopefully get to that soon.

**Comment by frankschlegel** [comment]
I just pushed a small fix that should prevent SwiftUI view redrawing for every video frame. This might improve performance.
Please let me know if this helps.

**Comment by hahmed1** [comment]
Hello, thanks for the response.  

I am testing with an iPhone XR.  I am still seeing the same frame rate (~16 FPS).

**Comment by hahmed1** [comment]
Hi Frank, 

I will close this issue.  It turned out that my UIKit code was actually down-sampling the video source.  When I compare your code with the UIKit w/o downsampling, it looks like the results are very similar. Sorry for the confusion!

**Comment by frankschlegel** [comment]
Thanks for the clarification! 🙂
